# cargo-deny configuration for Brioche
# https://embarkstudios.github.io/cargo-deny/index.html

[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "aarch64-unknown-linux-gnu" },
  { triple = "x86_64-pc-windows-msvc" },
  { triple = "aarch64-apple-darwin" },
  { triple = "x86_64-apple-darwin" },
  { triple = "wasm32-unknown-unknown" },
]
all-features = true

[licenses]
confidence-threshold = 0.9
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MPL-2.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "Zlib",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow-workspace = false

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = ["brio-labs"]
