//! Book I — The Core Book: Extension type system and `ExtensionStorage` foundation.
//!
//! This module upholds:
//! - I-Core-ExtensionType: Compile-time verified extension types via `BriocheExtensionType`.
//! - I-Core-VTableClone: VTable provides `clone_box`, `serialize`, `deserialize` for COW rollback.
//! - I-Core-ExtO1: O(log n) typed access by `TypeId` (n = registered types, typically < 20).
//! - I-Core-NoUnsafe: `ExtensionStorage` contains no `unsafe` code.
//!
//! Refs: SPECS.md §3.1, §3.2

use crate::CycleRollbackPolicy;
use std::any::{Any, TypeId};
use std::cell::Cell;
use std::collections::{BTreeMap, BTreeSet};

/// Snapshot strategy for COW rollback.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SnapshotStrategy {
    /// Full clone (default for small types, < 1 KB).
    FullClone,
    /// No snapshot — rollback forbidden for this type.
    NoSnapshot,
    /// Incremental snapshot: only modified fields cloned.
    Incremental,
    /// Priority full clone — exempt from `max_cow_bytes_per_hook` threshold.
    CriticalFullClone,
}

/// Serialize a type-erased instance to a binary blob.
pub type SerializeFn = fn(&dyn Any) -> Result<Vec<u8>, String>;

/// Deserialize a binary blob into a type-erased instance.
pub type DeserializeFn = fn(&[u8]) -> Result<Box<dyn Any + Send + Sync>, String>;

/// Clone a type-erased instance.
pub type CloneBoxFn = fn(&dyn Any) -> Box<dyn Any + Send + Sync>;

/// Estimate the instance weight in bytes.
pub type WeightFn = fn(&dyn Any) -> usize;

/// Construct a default type-erased instance.
pub type DefaultConstructFn = fn() -> Box<dyn Any + Send + Sync>;

/// Function table for per-type (de)serialization, cloning, and default construction.
///
/// Each `BriocheExtensionType` registers an `ExtVTable` at initialization.
/// The kernel uses this table to operate on type-erased extension instances
/// without dynamic dispatch overhead beyond a single function pointer call.
///
/// Refs: I-Core-VTableClone
#[derive(Clone)]
pub struct ExtVTable {
    /// Unique extension identifier, matching `BriocheExtensionType::EXT_ID`.
    pub ext_id: &'static str,
    /// Serialize a type-erased instance to a binary blob.
    ///
    /// Refs: I-Core-VTableClone
    pub serialize: SerializeFn,
    /// Deserialize a binary blob into a type-erased instance.
    ///
    /// Returns `Err` if the blob is corrupted or version-incompatible.
    /// The caller should fall back to `default_construct`.
    ///
    /// Refs: I-Core-VTableClone
    pub deserialize: DeserializeFn,
    /// Clone a type-erased instance.
    ///
    /// Used by `CycleRollbackPolicy` for granular COW snapshots.
    ///
    /// Refs: I-Core-VTableClone
    pub clone_box: CloneBoxFn,
    /// Estimate the instance weight in bytes.
    ///
    /// Used by `UndoFrameGuard` and `TieredUndoFrameGuard` to decide
    /// whether a type fits within the `max_cow_bytes_per_hook` budget.
    ///
    /// Complexity: O(serialization cost).
    pub estimated_weight_bytes: WeightFn,
    /// Recommended snapshot strategy for this type.
    ///
    /// `CriticalFullClone` types are always cloned by rollback guards,
    /// regardless of memory pressure.
    pub snapshot_strategy: SnapshotStrategy,
    /// Construct a default instance.
    ///
    /// Used by `get_or_insert_default` and `hydrate_plugin` as a fallback
    /// when deserialization fails.
    pub default_construct: DefaultConstructFn,
}

/// Private implementation detail for the sealed trait pattern.
///
/// Do not use this module directly. It is only public so that the
/// `brioche-macro` proc-macro can emit the required `Sealed` impl.
/// Any manual use is unsupported and may break without warning.
#[doc(hidden)]
pub mod __private {
    /// Sealed trait — prevents manual `BriocheExtensionType` implementations
    /// outside the SDK proc-macro.
    pub trait Sealed {}
}

/// Sealed trait for compile-time verified extension types.
///
/// Only implementations generated by `#[derive(BriocheExtensionType)]`
/// are valid. Manual implementations outside the SDK are prevented by
/// the sealed trait pattern.
///
/// # Sealed trait
///
/// This trait is sealed: the `__private::Sealed` supertrait cannot be
/// implemented outside `brioche-core` and `brioche-macro`. Any manual
/// `impl BriocheExtensionType for MyType` will fail to compile because
/// the compiler cannot find an `impl __private::Sealed for MyType`.
pub trait BriocheExtensionType:
    __private::Sealed
    + Any
    + Send
    + Sync
    + Clone
    + Default
    + serde::Serialize
    + serde::de::DeserializeOwned
{
    /// Unique extension identifier, respecting `crate::type_name` format.
    const EXT_ID: &'static str;

    /// Estimated weight in bytes for COW snapshot decisions.
    fn estimated_weight_bytes(&self) -> usize;

    /// Recommended snapshot strategy for this type.
    fn snapshot_strategy() -> SnapshotStrategy;

    /// Build the function table for this type.
    ///
    /// This is used by `ExtensionStorage` to perform type-erased
    /// operations (serialization, deserialization, cloning, default
    /// construction) without knowing the concrete type at compile time.
    fn build_vtable() -> ExtVTable
    where
        Self: Sized;
}

/// Type-safe runtime storage for plugin extension state.
///
/// `ExtensionStorage` provides O(log n) typed access to extension instances
/// by `TypeId` (n = number of registered types, typically < 20), with
/// automatic binary persistence via `ExtVTable`.
///
/// # Architecture
///
/// - `hot_map`: in-memory `BTreeMap` for typed access. Not persisted.
/// - `cold_snapshot`: binary blobs indexed by `EXT_ID`, persisted on `insert`.
/// - `registry`: `ExtVTable` instances populated at initialization.
/// - `rollback_policy`: owned `CycleRollbackPolicy` stored in a `Cell` so it
///   can be temporarily removed during COW snapshot callbacks without raw
///   pointers or borrow conflicts.
///
/// # Invariants
///
/// - All maps use `BTreeMap` for determinism; no `HashMap` in Core.
/// - Typed extension access is O(log n) by `TypeId`.
/// - **Zero `unsafe` in this module.** The previous `NonNull` observer
///   pattern is replaced by `Cell` ownership.
///
/// Refs: I-Core-ExtO1, I-Core-VTableClone, I-Core-NoUnsafe
pub struct ExtensionStorage {
    hot_map: BTreeMap<TypeId, Box<dyn Any + Send + Sync>>,
    cold_snapshot: BTreeMap<&'static str, Vec<u8>>,
    registry: BTreeMap<TypeId, ExtVTable>,
    ext_id_to_type_id: BTreeMap<&'static str, TypeId>,
    /// Owned rollback policy during a monitored hook. `None` when no hook
    /// is active. Stored in `Cell` so it can be taken/restored around
    /// `on_mutation` calls without borrow conflicts or raw pointers.
    rollback_policy: Cell<Option<Box<dyn CycleRollbackPolicy>>>,
    /// Types already snapshotted in the current hook. Prevents duplicate COW
    /// clones when a plugin calls `get_mut` multiple times for the same type.
    snapshotted_this_hook: BTreeSet<TypeId>,
}

impl Default for ExtensionStorage {
    fn default() -> Self {
        Self::new()
    }
}

impl ExtensionStorage {
    /// Create an empty `ExtensionStorage`.
    ///
    /// Complexity: O(1). Allocates empty maps.
    pub fn new() -> Self {
        Self {
            hot_map: BTreeMap::new(),
            cold_snapshot: BTreeMap::new(),
            registry: BTreeMap::new(),
            ext_id_to_type_id: BTreeMap::new(),
            rollback_policy: Cell::new(None),
            snapshotted_this_hook: BTreeSet::new(),
        }
    }

    /// Register a type's `ExtVTable`.
    ///
    /// This must be called (either explicitly or via `insert` /
    /// `get_or_insert_default`) before the type can be used.
    ///
    /// Complexity: O(log n). Two `BTreeMap` insertions.
    pub fn register<T>(&mut self)
    where
        T: BriocheExtensionType + 'static,
    {
        let vtable = T::build_vtable();
        let type_id = TypeId::of::<T>();
        self.ext_id_to_type_id.insert(vtable.ext_id, type_id);
        self.registry.insert(type_id, vtable);
    }

    /// Insert a typed value into storage.
    ///
    /// The value is serialized to a binary blob (via `ExtVTable::serialize`)
    /// and stored in `cold_snapshot`, then placed in `hot_map` for fast
    /// access.
    ///
    /// # Errors
    ///
    /// Returns `BriocheError::Serialization` if postcard serialization fails.
    /// This indicates a contract violation in the `BriocheExtensionType` impl.
    ///
    /// Complexity: O(serialization cost). Two `BTreeMap` insertions.
    pub fn insert<T>(&mut self, value: T) -> Result<(), crate::BriocheError>
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        if !self.registry.contains_key(&type_id) {
            self.register::<T>();
        }
        let Some(vtable) = self.registry.get(&type_id) else {
            return Err(crate::BriocheError::StorageAccess(
                "missing vtable after registration".into(),
            ));
        };
        let blob = (vtable.serialize)(&value).map_err(crate::BriocheError::Serialization)?;
        self.cold_snapshot.insert(vtable.ext_id, blob);
        // Snapshot the OLD value (if any) BEFORE replacing it, so rollback
        // restores the pre-mutation state. I-Gov-Rollback-BestEffort.
        self.notify_cow_on_first_mutation(type_id);
        self.hot_map.insert(type_id, Box::new(value));
        Ok(())
    }

    /// Get a mutable reference to a typed extension, if present.
    ///
    /// Complexity: O(log n). One `BTreeMap` lookup plus `downcast_mut`.
    ///
    /// Refs: I-Core-ExtO1
    pub fn get_mut<T>(&mut self) -> Option<&mut T>
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        self.notify_cow_on_first_mutation(type_id);
        self.hot_map
            .get_mut(&type_id)
            .and_then(|any| any.downcast_mut::<T>())
    }

    /// Get an immutable reference to a typed extension, if present.
    ///
    /// Complexity: O(log n). One `BTreeMap` lookup plus `downcast_ref`.
    /// No COW snapshot is triggered.
    ///
    /// Refs: I-Core-ExtO1
    pub fn get<T>(&self) -> Option<&T>
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        self.hot_map
            .get(&type_id)
            .and_then(|any| any.downcast_ref::<T>())
    }

    /// Run a closure with a mutable reference to a typed extension,
    /// inserting the default if absent.
    ///
    /// If the type is not in `hot_map`, attempts to restore from
    /// `cold_snapshot` via `ExtVTable::deserialize`. On deserialization
    /// failure, falls back to `ExtVTable::default_construct`.
    ///
    /// This method is infallible: it always invokes `f` with a valid
    /// `&mut T`. It uses a closure instead of returning `&mut T` directly
    /// because `Any::downcast_mut`'s `Option<&mut T>` forces the borrow
    /// checker to extend the `BTreeMap` borrow to the end of the caller's
    /// scope, which caused either `unsafe`, `Box::leak`, or double-borrow
    /// workarounds in previous designs. The closure form is fully safe,
    /// fully deterministic, and matches PHILOSOPHY.md §2.3
    /// (borrow-checker-friendly APIs).
    ///
    /// The closure is `FnMut` so it can be retried if a defensive loop
    /// iteration is ever needed. In correct operation the loop exits on
    /// the first iteration.
    ///
    /// Complexity: O(log n) amortized. One `BTreeMap` lookup plus optional
    /// deserialization.
    ///
    /// Refs: I-Core-ExtO1
    pub fn with_or_insert_default<T, R>(&mut self, mut f: impl FnMut(&mut T) -> R) -> R
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        if !self.registry.contains_key(&type_id) {
            self.register::<T>();
        }
        if !self.hot_map.contains_key(&type_id) {
            let value: Box<dyn Any + Send + Sync> =
                if let Some(vtable) = self.registry.get(&type_id) {
                    self.cold_snapshot
                        .get(vtable.ext_id)
                        .and_then(|blob| (vtable.deserialize)(blob).ok())
                        .unwrap_or_else(|| (vtable.default_construct)())
                } else {
                    // Defensive: vtable should have been registered just above.
                    Box::new(T::default())
                };
            self.hot_map.insert(type_id, value);
        }
        // Notify COW observer now that the value is guaranteed to exist.
        self.notify_cow_on_first_mutation(type_id);

        // Defensive: type-check the entry and correct it if a previous bug
        // or memory corruption left the wrong type at this TypeId. We use a
        // loop rather than recursion so the closure (`FnMut`) can be retried;
        // in correct operation the loop exits on the first iteration.
        loop {
            let mut value = match self.hot_map.remove(&type_id) {
                Some(v) => v,
                None => Box::new(T::default()),
            };
            if value.downcast_ref::<T>().is_none() {
                value = Box::new(T::default());
            }
            self.hot_map.insert(type_id, value);

            let mut result: Option<R> = None;
            if let Some(entry) = self.hot_map.get_mut(&type_id)
                && let Some(typed) = entry.downcast_mut::<T>()
            {
                result = Some(f(typed));
            }
            if let Some(r) = result {
                return r;
            }
        }
    }

    /// Hydrate a plugin from an external raw blob.
    ///
    /// Looks up the `ext_id` in the registry, deserializes the blob,
    /// and inserts the result into `hot_map`. On deserialization failure,
    /// falls back to the default value. Returns `true` if the `ext_id`
    /// was known.
    ///
    /// This is used by the shell when loading persisted plugin state
    /// from disk.
    ///
    /// Complexity: O(deserialization cost). Two `BTreeMap` insertions.
    pub fn hydrate_plugin(&mut self, ext_id: &str, blob: &[u8]) -> bool {
        let Some(&type_id) = self.ext_id_to_type_id.get(ext_id) else {
            return false;
        };
        let Some(vtable) = self.registry.get(&type_id) else {
            return false;
        };
        let value: Box<dyn Any + Send + Sync> = match (vtable.deserialize)(blob) {
            Ok(val) => val,
            Err(_) => (vtable.default_construct)(),
        };
        self.hot_map.insert(type_id, value);
        self.cold_snapshot.insert(vtable.ext_id, blob.to_vec());
        true
    }

    /// Return a reference to the cold snapshot map.
    ///
    /// Used by persistence layers to extract binary blobs for disk write.
    ///
    /// Complexity: O(1). Returns a reference; no allocation.
    pub fn cold_snapshot(&self) -> &BTreeMap<&'static str, Vec<u8>> {
        &self.cold_snapshot
    }

    /// Insert a value into `hot_map` only, bypassing `cold_snapshot` serialization.
    ///
    /// Used by the kernel for transient per-cycle metadata such as
    /// `SessionSnapshot` that is fully reconstructed on every transition.
    ///
    /// Complexity: O(log n). One `BTreeMap` insertion; no serialization.
    ///
    /// Refs: I-Core-ExtO1
    pub fn insert_hot<T>(&mut self, value: T)
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        if !self.registry.contains_key(&type_id) {
            self.register::<T>();
        }
        // Hot-only mutations are also observable to plugins; snapshot old
        // state so rollback can restore it. I-Gov-Rollback-BestEffort.
        self.notify_cow_on_first_mutation(type_id);
        self.hot_map.insert(type_id, Box::new(value));
    }

    /// Set the owned COW rollback policy for the duration of a monitored hook.
    ///
    /// The engine transfers ownership to `ExtensionStorage`, retrieves it
    /// via `take_rollback_policy` after the hook, and drives the hook
    /// lifecycle through `begin_hook` / `commit_hook` / `rollback_hook`.
    /// This replaces the previous unsafe raw-pointer observer pattern.
    ///
    /// Complexity: O(1). No heap allocation.
    ///
    /// Refs: I-Gov-Rollback-BestEffort
    pub fn set_rollback_policy(&mut self, policy: Option<Box<dyn CycleRollbackPolicy>>) {
        self.rollback_policy.set(policy);
        self.snapshotted_this_hook.clear();
    }

    /// Take back the owned COW rollback policy.
    ///
    /// Returns `None` if no policy was set.
    ///
    /// Complexity: O(1). No heap allocation.
    pub fn take_rollback_policy(&mut self) -> Option<Box<dyn CycleRollbackPolicy>> {
        self.rollback_policy.take()
    }

    /// Begin a monitored hook: calls `begin_hook` on the policy and resets
    /// the per-hook snapshot tracking.
    ///
    /// Complexity: O(1) + policy cost.
    pub fn begin_hook(&mut self) {
        let policy = self.rollback_policy.take();
        if let Some(mut p) = policy {
            p.begin_hook();
            self.rollback_policy.set(Some(p));
        }
        self.snapshotted_this_hook.clear();
    }

    /// Commit the current hook: calls `commit_hook` on the policy.
    ///
    /// Complexity: O(1) + policy cost.
    pub fn commit_hook(&mut self) {
        let policy = self.rollback_policy.take();
        if let Some(mut p) = policy {
            p.commit_hook(self);
            self.rollback_policy.set(Some(p));
        }
    }

    /// Rollback the current hook: calls `rollback_hook` on the policy.
    ///
    /// Complexity: O(1) + policy cost.
    pub fn rollback_hook(&mut self) {
        let policy = self.rollback_policy.take();
        if let Some(mut p) = policy {
            p.rollback_hook(self);
            self.rollback_policy.set(Some(p));
        }
    }

    /// Update an existing `hot_map` entry in-place, avoiding allocation if
    /// the slot is already warm. Falls back to `insert_hot` on first use.
    ///
    /// Used by the kernel for `SessionSnapshot` injection to eliminate
    /// per-hook heap allocations after the initial warm-up.
    ///
    /// Complexity: O(log n). Zero allocation on the warm path.
    ///
    /// Refs: I-Core-ExtO1, I-Core-ChunkBudget
    pub fn update_hot<T>(&mut self, value: T)
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        if !self.registry.contains_key(&type_id) {
            self.register::<T>();
        }
        // Snapshot the existing value before in-place mutation so rollback
        // can restore the previous snapshot. I-Gov-Rollback-BestEffort.
        self.notify_cow_on_first_mutation(type_id);
        if let Some(existing) = self
            .hot_map
            .get_mut(&type_id)
            .and_then(|any| any.downcast_mut::<T>())
        {
            *existing = value;
        } else {
            self.hot_map.insert(type_id, Box::new(value));
        }
    }

    /// Restore a type-erased value into `hot_map` from a COW snapshot.
    ///
    /// Used by `CycleRollbackPolicy` implementations during `rollback_hook`.
    /// Does **not** update `cold_snapshot` — rollback only affects hot state.
    ///
    /// Complexity: O(log n). One `BTreeMap` insertion; no serialization.
    ///
    /// Refs: I-Gov-Rollback-BestEffort
    pub fn restore_boxed(&mut self, type_id: TypeId, value: Box<dyn Any + Send + Sync>) {
        self.hot_map.insert(type_id, value);
    }

    /// Notify the COW policy on first mutation access for a type in this hook.
    ///
    /// Uses `Cell::take` to temporarily remove the policy, avoiding both
    /// raw pointers and borrow conflicts with `self.hot_map`. The policy
    /// is restored immediately after the callback.
    ///
    /// This method contains **no unsafe code**.
    fn notify_cow_on_first_mutation(&mut self, type_id: TypeId) {
        if self.snapshotted_this_hook.contains(&type_id) {
            return;
        }
        let Some(vtable) = self.registry.get(&type_id) else {
            return;
        };

        // Scoped block limits the immutable borrow of `self.hot_map` so
        // `self.snapshotted_this_hook.insert` can run afterwards.
        {
            let Some(current) = self.hot_map.get(&type_id) else {
                return;
            };
            let policy = self.rollback_policy.take();
            if let Some(mut p) = policy {
                p.on_mutation(type_id, vtable, current.as_ref());
                self.rollback_policy.set(Some(p));
            }
        }
        self.snapshotted_this_hook.insert(type_id);
    }

    /// Remove a type from `hot_map` without touching `cold_snapshot`.
    ///
    /// This can be used to evict cold entries while keeping the
    /// persisted blob intact.
    ///
    /// Complexity: O(log n). One `BTreeMap` removal.
    pub fn evict_from_hot<T>(&mut self) -> bool
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        self.hot_map.remove(&type_id).is_some()
    }
}
