//! Book I — The Core Book: Extension type system and `ExtensionStorage` foundation.
//!
//! This module upholds:
//! - I-Core-ExtensionType: Compile-time verified extension types via `BriocheExtensionType`.
//! - I-Core-VTableClone: VTable provides `clone_box`, `serialize`, `deserialize` for COW rollback.
//! - I-Core-ExtO1: O(1) typed access by `TypeId`.
//!
//! Refs: SPECS.md §3.1, §3.2

use std::any::Any;

/// Snapshot strategy for COW rollback.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SnapshotStrategy {
    /// Full clone (default for small types, < 1 KB).
    FullClone,
    /// No snapshot — rollback forbidden for this type.
    NoSnapshot,
    /// Incremental snapshot: only modified fields cloned.
    Incremental,
    /// Priority full clone — exempt from `max_cow_bytes_per_hook` threshold.
    CriticalFullClone,
}

/// Private implementation detail for the sealed trait pattern.
///
/// Do not use this module directly. It is only public so that the
/// `brioche-macro` proc-macro can emit the required `Sealed` impl.
/// Any manual use is unsupported and may break without warning.
#[doc(hidden)]
pub mod __private {
    /// Sealed trait — prevents manual `BriocheExtensionType` implementations
    /// outside the SDK proc-macro.
    pub trait Sealed {}
}

/// Sealed trait for compile-time verified extension types.
///
/// Only implementations generated by `#[derive(BriocheExtensionType)]`
/// are valid. Manual implementations outside the SDK are prevented by
/// the sealed trait pattern.
///
/// # Sealed trait
///
/// This trait is sealed: the `__private::Sealed` supertrait cannot be
/// implemented outside `brioche-core` and `brioche-macro`. Any manual
/// `impl BriocheExtensionType for MyType` will fail to compile because
/// the compiler cannot find an `impl __private::Sealed for MyType`.
pub trait BriocheExtensionType: __private::Sealed + Any + Send + Sync + Clone {
    /// Unique extension identifier, respecting `crate::type_name` format.
    const EXT_ID: &'static str;

    /// Estimated weight in bytes for COW snapshot decisions.
    fn estimated_weight_bytes(&self) -> usize;

    /// Recommended snapshot strategy for this type.
    fn snapshot_strategy() -> SnapshotStrategy;
}
