//! Book I — The Core Book: Extension type system and `ExtensionStorage` foundation.
//!
//! This module upholds:
//! - I-Core-ExtensionType: Compile-time verified extension types via `BriocheExtensionType`.
//! - I-Core-VTableClone: VTable provides `clone_box`, `serialize`, `deserialize` for COW rollback.
//! - I-Core-ExtO1: O(log n) typed access by `TypeId` (n = registered types, typically < 20).
//!
//! Refs: SPECS.md §3.1, §3.2

use std::any::{Any, TypeId};
use std::collections::{BTreeMap, BTreeSet};

use crate::CycleRollbackPolicy;

/// Snapshot strategy for COW rollback.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SnapshotStrategy {
    /// Full clone (default for small types, < 1 KB).
    FullClone,
    /// No snapshot — rollback forbidden for this type.
    NoSnapshot,
    /// Incremental snapshot: only modified fields cloned.
    Incremental,
    /// Priority full clone — exempt from `max_cow_bytes_per_hook` threshold.
    CriticalFullClone,
}

/// Serialize a type-erased instance to a binary blob.
pub type SerializeFn = fn(&dyn Any) -> Vec<u8>;

/// Deserialize a binary blob into a type-erased instance.
pub type DeserializeFn = fn(&[u8]) -> Result<Box<dyn Any + Send + Sync>, String>;

/// Clone a type-erased instance.
pub type CloneBoxFn = fn(&dyn Any) -> Box<dyn Any + Send + Sync>;

/// Estimate the instance weight in bytes.
pub type WeightFn = fn(&dyn Any) -> usize;

/// Construct a default type-erased instance.
pub type DefaultConstructFn = fn() -> Box<dyn Any + Send + Sync>;

/// Function table for per-type (de)serialization, cloning, and default construction.
///
/// Each `BriocheExtensionType` registers an `ExtVTable` at initialization.
/// The kernel uses this table to operate on type-erased extension instances
/// without dynamic dispatch overhead beyond a single function pointer call.
///
/// Refs: I-Core-VTableClone
#[derive(Clone)]
pub struct ExtVTable {
    /// Unique extension identifier, matching `BriocheExtensionType::EXT_ID`.
    pub ext_id: &'static str,
    /// Serialize a type-erased instance to a binary blob.
    ///
    /// Refs: I-Core-VTableClone
    pub serialize: SerializeFn,
    /// Deserialize a binary blob into a type-erased instance.
    ///
    /// Returns `Err` if the blob is corrupted or version-incompatible.
    /// The caller should fall back to `default_construct`.
    ///
    /// Refs: I-Core-VTableClone
    pub deserialize: DeserializeFn,
    /// Clone a type-erased instance.
    ///
    /// Used by `CycleRollbackPolicy` for granular COW snapshots.
    ///
    /// Refs: I-Core-VTableClone
    pub clone_box: CloneBoxFn,
    /// Estimate the instance weight in bytes.
    ///
    /// Used by `UndoFrameGuard` and `TieredUndoFrameGuard` to decide
    /// whether a type fits within the `max_cow_bytes_per_hook` budget.
    ///
    /// Complexity: O(serialization cost).
    pub estimated_weight_bytes: WeightFn,
    /// Recommended snapshot strategy for this type.
    ///
    /// `CriticalFullClone` types are always cloned by rollback guards,
    /// regardless of memory pressure.
    pub snapshot_strategy: SnapshotStrategy,
    /// Construct a default instance.
    ///
    /// Used by `get_or_insert_default` and `hydrate_plugin` as a fallback
    /// when deserialization fails.
    pub default_construct: DefaultConstructFn,
}

/// Private implementation detail for the sealed trait pattern.
///
/// Do not use this module directly. It is only public so that the
/// `brioche-macro` proc-macro can emit the required `Sealed` impl.
/// Any manual use is unsupported and may break without warning.
#[doc(hidden)]
pub mod __private {
    /// Sealed trait — prevents manual `BriocheExtensionType` implementations
    /// outside the SDK proc-macro.
    pub trait Sealed {}
}

/// Sealed trait for compile-time verified extension types.
///
/// Only implementations generated by `#[derive(BriocheExtensionType)]`
/// are valid. Manual implementations outside the SDK are prevented by
/// the sealed trait pattern.
///
/// # Sealed trait
///
/// This trait is sealed: the `__private::Sealed` supertrait cannot be
/// implemented outside `brioche-core` and `brioche-macro`. Any manual
/// `impl BriocheExtensionType for MyType` will fail to compile because
/// the compiler cannot find an `impl __private::Sealed for MyType`.
pub trait BriocheExtensionType:
    __private::Sealed
    + Any
    + Send
    + Sync
    + Clone
    + Default
    + serde::Serialize
    + serde::de::DeserializeOwned
{
    /// Unique extension identifier, respecting `crate::type_name` format.
    const EXT_ID: &'static str;

    /// Estimated weight in bytes for COW snapshot decisions.
    fn estimated_weight_bytes(&self) -> usize;

    /// Recommended snapshot strategy for this type.
    fn snapshot_strategy() -> SnapshotStrategy;

    /// Build the function table for this type.
    ///
    /// This is used by `ExtensionStorage` to perform type-erased
    /// operations (serialization, deserialization, cloning, default
    /// construction) without knowing the concrete type at compile time.
    fn build_vtable() -> ExtVTable
    where
        Self: Sized;
}

/// Type-safe runtime storage for plugin extension state.
///
/// `ExtensionStorage` provides O(log n) typed access to extension instances
/// by `TypeId` (n = number of registered types, typically < 20), with
/// automatic binary persistence via `ExtVTable`.
///
/// # Architecture
///
/// - `hot_map`: in-memory `BTreeMap` for typed access. Not persisted.
/// - `cold_snapshot`: binary blobs indexed by `EXT_ID`, persisted on `insert`.
/// - `registry`: `ExtVTable` instances populated at initialization.
///
/// # Invariants
///
/// - All maps use `BTreeMap` for determinism; no `HashMap` in Core.
/// - Typed extension access is O(log n) by `TypeId` and infallible after
///   `get_or_insert_default`.
///
/// Refs: I-Core-ExtO1, I-Core-VTableClone
pub struct ExtensionStorage {
    hot_map: BTreeMap<TypeId, Box<dyn Any + Send + Sync>>,
    cold_snapshot: BTreeMap<String, Vec<u8>>,
    registry: BTreeMap<TypeId, ExtVTable>,
    ext_id_to_type_id: BTreeMap<String, TypeId>,
    /// Owned `CycleRollbackPolicy` temporarily attached during a monitored hook.
    /// The engine moves the policy into storage before each hook and retrieves
    /// it afterward. No raw pointers, no `unsafe`.
    rollback_policy: Option<Box<dyn CycleRollbackPolicy>>,
    /// Types already snapshotted in the current hook. Prevents duplicate COW
    /// clones when a plugin calls `get_mut` multiple times for the same type.
    snapshotted_this_hook: BTreeSet<TypeId>,
}

impl Default for ExtensionStorage {
    fn default() -> Self {
        Self::new()
    }
}

impl ExtensionStorage {
    /// Create an empty `ExtensionStorage`.
    ///
    /// Complexity: O(1). Allocates empty maps.
    ///
    /// Refs: I-Core-Pure
    pub fn new() -> Self {
        Self {
            hot_map: BTreeMap::new(),
            cold_snapshot: BTreeMap::new(),
            registry: BTreeMap::new(),
            ext_id_to_type_id: BTreeMap::new(),
            rollback_policy: None,
            snapshotted_this_hook: BTreeSet::new(),
        }
    }

    /// Register a type's `ExtVTable`.
    ///
    /// This must be called (either explicitly or via `insert` /
    /// `get_or_insert_default`) before the type can be used.
    ///
    /// Complexity: O(log n). Two `BTreeMap` insertions.
    ///
    /// Refs: I-Core-Pure
    pub fn register<T>(&mut self)
    where
        T: BriocheExtensionType + 'static,
    {
        let vtable = T::build_vtable();
        let type_id = TypeId::of::<T>();
        self.ext_id_to_type_id
            .insert(vtable.ext_id.to_string(), type_id);
        self.registry.insert(type_id, vtable);
    }

    /// Insert a typed value into storage.
    ///
    /// The value is serialized to a binary blob (via `ExtVTable::serialize`)
    /// and stored in `cold_snapshot`, then placed in `hot_map` for fast
    /// access.
    ///
    /// Complexity: O(serialization cost). Two `BTreeMap` insertions.
    ///
    /// Refs: I-Core-Pure
    pub fn insert<T>(&mut self, value: T)
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        if !self.registry.contains_key(&type_id) {
            self.register::<T>();
        }
        if let Some(vtable) = self.registry.get(&type_id) {
            let blob = (vtable.serialize)(&value);
            self.cold_snapshot.insert(vtable.ext_id.to_string(), blob);
            self.hot_map.insert(type_id, Box::new(value));
        }
        // Defensive: if vtable is missing, value is silently dropped.
        // This should never happen because register was called above.
    }

    /// Get a mutable reference to a typed extension, if present.
    ///
    /// Complexity: O(log n). One `BTreeMap` lookup plus `downcast_mut`.
    ///
    /// Refs: I-Core-ExtO1
    pub fn get_mut<T>(&mut self) -> Option<&mut T>
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        self.notify_cow_on_first_mutation(type_id);
        self.hot_map
            .get_mut(&type_id)
            .and_then(|any| any.downcast_mut::<T>())
    }

    /// Get a mutable reference to a typed extension, inserting the default
    /// if absent.
    ///
    /// If the type is not in `hot_map`, attempts to restore from
    /// `cold_snapshot` via `ExtVTable::deserialize`. On deserialization
    /// failure, falls back to `ExtVTable::default_construct`.
    ///
    /// This method is infallible: it always returns a valid `&mut T`.
    ///
    /// Complexity: O(log n) amortized. One `BTreeMap` lookup plus optional
    /// deserialization.
    ///
    /// Refs: I-Core-ExtO1
    pub fn get_or_insert_default<T>(&mut self) -> &mut T
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        if !self.registry.contains_key(&type_id) {
            self.register::<T>();
        }
        if !self.hot_map.contains_key(&type_id) {
            let value: Box<dyn Any + Send + Sync> =
                if let Some(vtable) = self.registry.get(&type_id) {
                    self.cold_snapshot
                        .get(vtable.ext_id)
                        .and_then(|blob| (vtable.deserialize)(blob).ok())
                        .unwrap_or_else(|| (vtable.default_construct)())
                } else {
                    // Defensive: vtable should have been registered just above.
                    Box::new(T::default())
                };
            self.hot_map.insert(type_id, value);
        }
        // Notify COW observer now that the value is guaranteed to exist.
        self.notify_cow_on_first_mutation(type_id);
        // Infallible: we just ensured (or verified) that hot_map contains
        // Box<T> for this type_id. If a type mismatch occurs, it indicates
        // a fundamental invariant violation; we leak rather than panic
        // to uphold I-Core-NoPanic.
        self.hot_map
            .get_mut(&type_id)
            .and_then(|any| any.downcast_mut::<T>())
            .unwrap_or_else(|| Box::leak(Box::new(T::default())))
    }

    /// Hydrate a plugin from an external raw blob.
    ///
    /// Looks up the `ext_id` in the registry, deserializes the blob,
    /// and inserts the result into `hot_map`. On deserialization failure,
    /// falls back to the default value. Returns `true` if the `ext_id`
    /// was known.
    ///
    /// This is used by the shell when loading persisted plugin state
    /// from disk.
    ///
    /// Complexity: O(deserialization cost). Two `BTreeMap` insertions.
    ///
    /// Refs: I-Core-Pure
    pub fn hydrate_plugin(&mut self, ext_id: &str, blob: &[u8]) -> bool {
        let Some(&type_id) = self.ext_id_to_type_id.get(ext_id) else {
            return false;
        };
        let Some(vtable) = self.registry.get(&type_id) else {
            return false;
        };
        let value: Box<dyn Any + Send + Sync> = match (vtable.deserialize)(blob) {
            Ok(val) => val,
            Err(_) => (vtable.default_construct)(),
        };
        self.hot_map.insert(type_id, value);
        self.cold_snapshot.insert(ext_id.to_string(), blob.to_vec());
        true
    }

    /// Return a reference to the cold snapshot map.
    ///
    /// Used by persistence layers to extract binary blobs for disk write.
    ///
    /// Complexity: O(1). Returns a reference; no allocation.
    ///
    /// Refs: I-Core-Pure
    pub fn cold_snapshot(&self) -> &BTreeMap<String, Vec<u8>> {
        &self.cold_snapshot
    }

    /// Attach a `CycleRollbackPolicy` for the duration of a monitored hook.
    ///
    /// Complexity: O(1). No heap allocation.
    ///
    /// Refs: I-Gov-Rollback-BestEffort
    pub fn attach_rollback_policy(&mut self, policy: Box<dyn CycleRollbackPolicy>) {
        self.rollback_policy = Some(policy);
        self.snapshotted_this_hook.clear();
    }

    /// Detach the active `CycleRollbackPolicy`, returning it.
    ///
    /// Complexity: O(1). No heap allocation.
    ///
    /// Refs: I-Gov-Rollback-BestEffort
    pub fn detach_rollback_policy(&mut self) -> Option<Box<dyn CycleRollbackPolicy>> {
        self.snapshotted_this_hook.clear();
        self.rollback_policy.take()
    }

    /// Restore a type-erased value into `hot_map` from a COW snapshot.
    ///
    /// Used by `CycleRollbackPolicy` implementations during `rollback_hook`.
    /// Does **not** update `cold_snapshot` — rollback only affects hot state.
    ///
    /// Complexity: O(log n). One `BTreeMap` insertion; no serialization.
    ///
    /// Refs: I-Gov-Rollback-BestEffort
    pub fn restore_boxed(&mut self, type_id: TypeId, value: Box<dyn Any + Send + Sync>) {
        self.hot_map.insert(type_id, value);
    }

    /// Notify the COW observer on first mutation access for a type in this hook.
    fn notify_cow_on_first_mutation(&mut self, type_id: TypeId) {
        let Some(policy) = self.rollback_policy.as_mut() else {
            return;
        };
        if self.snapshotted_this_hook.contains(&type_id) {
            return;
        }
        let Some(vtable) = self.registry.get(&type_id) else {
            return;
        };
        let Some(current) = self.hot_map.get(&type_id) else {
            return;
        };
        policy.on_mutation(type_id, vtable, current.as_ref());
        self.snapshotted_this_hook.insert(type_id);
    }

    /// Remove a type from `hot_map` without touching `cold_snapshot`.
    ///
    /// This can be used to evict cold entries while keeping the
    /// persisted blob intact.
    ///
    /// Complexity: O(log n). One `BTreeMap` removal.
    ///
    /// Refs: I-Core-Pure
    pub fn evict_from_hot<T>(&mut self) -> bool
    where
        T: BriocheExtensionType + 'static,
    {
        let type_id = TypeId::of::<T>();
        self.hot_map.remove(&type_id).is_some()
    }
}
